version: "2"

linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - godox
    - ireturn
    - mnd
    - nlreturn
    - nonamedreturns
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl

  exclusions:
    rules:
      - path: 'framework/'
        linters:
          - cyclop
          - err113
          - funcorder
          - funlen
          - gochecknoglobals
          - gocognit
          - goconst
          - godoclint
          - govet
          - lll
          - nestif
          - nilnil
          - noinlineerr
          - paralleltest
          - staticcheck
          - wsl_v5

  settings:
    errcheck:
      check-type-assertions: true
    exhaustive:
      default-signifies-exhaustive: true
    govet:
      enable-all: true
    importas:
      no-unaliased: true
    revive:
      rules:
        - name: unexported-return
          disabled: true

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
